/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import com.mailodds.models.AddSuppressionRequestEntriesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyEntries 
 */


data class AddSuppressionRequest (

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<AddSuppressionRequestEntriesInner>

) {


}

