/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param s3Key S3 key from presigned upload
 * @param dedup 
 */


data class CreateJobFromS3Request (

    /* S3 key from presigned upload */
    @Json(name = "s3_key")
    val s3Key: kotlin.String,

    @Json(name = "dedup")
    val dedup: kotlin.Boolean? = false

) {


}

