/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Bulk jobs use the account's default validation policy. To use a specific policy, set it as default via the Policies API.
 *
 * @param emails List of emails to validate
 * @param dedup Remove duplicate emails
 * @param metadata Custom metadata for the job
 * @param webhookUrl URL for completion webhook
 * @param idempotencyKey Unique key for idempotent requests
 */


data class CreateJobRequest (

    /* List of emails to validate */
    @Json(name = "emails")
    val emails: kotlin.collections.List<kotlin.String>,

    /* Remove duplicate emails */
    @Json(name = "dedup")
    val dedup: kotlin.Boolean? = false,

    /* Custom metadata for the job */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null,

    /* URL for completion webhook */
    @Json(name = "webhook_url")
    val webhookUrl: java.net.URI? = null,

    /* Unique key for idempotent requests */
    @Json(name = "idempotency_key")
    val idempotencyKey: kotlin.String? = null

) {


}

