/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error Machine-readable error code
 * @param message Human-readable error message
 * @param schemaVersion 
 */


data class ErrorResponse (

    /* Machine-readable error code */
    @Json(name = "error")
    val error: kotlin.String,

    /* Human-readable error message */
    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null

) {


}

