/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import com.mailodds.models.PolicyRuleAction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Rule type determines how condition is evaluated
 * @param condition Condition depends on rule type. status_override: {status}, domain_filter: {domain_mode, domains}, check_requirement: {check, required}, sub_status_override: {sub_status}
 * @param action 
 * @param id 
 * @param sequence 
 * @param isEnabled 
 */


data class PolicyRule (

    /* Rule type determines how condition is evaluated */
    @Json(name = "type")
    val type: PolicyRule.Type,

    /* Condition depends on rule type. status_override: {status}, domain_filter: {domain_mode, domains}, check_requirement: {check, required}, sub_status_override: {sub_status} */
    @Json(name = "condition")
    val condition: kotlin.Any,

    @Json(name = "action")
    val action: PolicyRuleAction,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "sequence")
    val sequence: kotlin.Int? = null,

    @Json(name = "is_enabled")
    val isEnabled: kotlin.Boolean? = null

) {

    /**
     * Rule type determines how condition is evaluated
     *
     * Values: status_override,domain_filter,check_requirement,sub_status_override
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "status_override") status_override("status_override"),
        @Json(name = "domain_filter") domain_filter("domain_filter"),
        @Json(name = "check_requirement") check_requirement("check_requirement"),
        @Json(name = "sub_status_override") sub_status_override("sub_status_override");
    }

}

