/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import com.mailodds.models.Policy
import com.mailodds.models.PolicyListResponseLimits

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param policies 
 * @param limits 
 */


data class PolicyListResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "policies")
    val policies: kotlin.collections.List<Policy>? = null,

    @Json(name = "limits")
    val limits: PolicyListResponseLimits? = null

) {


}

