/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param action 
 */


data class PolicyRuleAction (

    @Json(name = "action")
    val action: PolicyRuleAction.Action? = null

) {

    /**
     * 
     *
     * Values: accept,reject,accept_with_caution,do_not_mail,review
     */
    @JsonClass(generateAdapter = false)
    enum class Action(val value: kotlin.String) {
        @Json(name = "accept") accept("accept"),
        @Json(name = "reject") reject("reject"),
        @Json(name = "accept_with_caution") accept_with_caution("accept_with_caution"),
        @Json(name = "do_not_mail") do_not_mail("do_not_mail"),
        @Json(name = "review") review("review");
    }

}

