/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import com.mailodds.models.PolicyPresetsResponsePresetsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param presets 
 */


data class PolicyPresetsResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "presets")
    val presets: kotlin.collections.List<PolicyPresetsResponsePresetsInner>? = null

) {


}

