/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param original Original validation result before policy
 * @param modified Result after policy applied
 * @param matchedRule The rule that matched, or null if none matched
 * @param rulesEvaluated 
 */


data class PolicyTestResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    /* Original validation result before policy */
    @Json(name = "original")
    val original: kotlin.Any? = null,

    /* Result after policy applied */
    @Json(name = "modified")
    val modified: kotlin.Any? = null,

    /* The rule that matched, or null if none matched */
    @Json(name = "matched_rule")
    val matchedRule: kotlin.Any? = null,

    @Json(name = "rules_evaluated")
    val rulesEvaluated: kotlin.Int? = null

) {


}

