/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param `value` 
 * @param reason 
 * @param createdAt 
 */


data class SuppressionEntry (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "type")
    val type: SuppressionEntry.Type? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: email,domain
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "email") email("email"),
        @Json(name = "domain") domain("domain");
    }

}

