/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import com.mailodds.models.Pagination
import com.mailodds.models.SuppressionEntry

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param propertyEntries 
 * @param pagination 
 */


data class SuppressionListResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<SuppressionEntry>? = null,

    @Json(name = "pagination")
    val pagination: Pagination? = null

) {


}

