/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param domain 
 */


data class SuppressionStatsResponseByType (

    @Json(name = "email")
    val email: kotlin.Int? = null,

    @Json(name = "domain")
    val domain: kotlin.Int? = null

) {


}

