/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param validations Total validations in window
 * @param creditsUsed Credits consumed
 */


data class TelemetrySummaryTotals (

    /* Total validations in window */
    @Json(name = "validations")
    val validations: kotlin.Int? = null,

    /* Credits consumed */
    @Json(name = "creditsUsed")
    val creditsUsed: kotlin.Int? = null

) {


}

