/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param domain 
 * @param volume 
 * @param deliverable 
 * @param reject 
 * @param unknown 
 * @param catchAll 
 */


data class TelemetrySummaryTopDomainsInner (

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "volume")
    val volume: kotlin.Int? = null,

    @Json(name = "deliverable")
    val deliverable: java.math.BigDecimal? = null,

    @Json(name = "reject")
    val reject: java.math.BigDecimal? = null,

    @Json(name = "unknown")
    val unknown: java.math.BigDecimal? = null,

    @Json(name = "catchAll")
    val catchAll: java.math.BigDecimal? = null

) {


}

