/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reason 
 * @param count 
 */


data class TelemetrySummaryTopReasonsInner (

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "count")
    val count: kotlin.Int? = null

) {


}

