/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email Email address to validate
 * @param policyId Optional policy ID to use instead of default policy
 */


data class ValidateRequest (

    /* Email address to validate */
    @Json(name = "email")
    val email: kotlin.String,

    /* Optional policy ID to use instead of default policy */
    @Json(name = "policy_id")
    val policyId: kotlin.Int? = null

) {


}

