/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import com.mailodds.models.ValidationResponseSuppressionMatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param status Validation status
 * @param action Recommended action
 * @param schemaVersion 
 * @param subStatus Detailed status reason
 * @param domain 
 * @param mxFound 
 * @param smtpCheck 
 * @param disposable 
 * @param roleAccount 
 * @param freeProvider 
 * @param suppressionMatch 
 */


data class ValidationResponse (

    @Json(name = "email")
    val email: kotlin.String,

    /* Validation status */
    @Json(name = "status")
    val status: ValidationResponse.Status,

    /* Recommended action */
    @Json(name = "action")
    val action: ValidationResponse.Action,

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    /* Detailed status reason */
    @Json(name = "sub_status")
    val subStatus: kotlin.String? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "mx_found")
    val mxFound: kotlin.Boolean? = null,

    @Json(name = "smtp_check")
    val smtpCheck: kotlin.Boolean? = null,

    @Json(name = "disposable")
    val disposable: kotlin.Boolean? = null,

    @Json(name = "role_account")
    val roleAccount: kotlin.Boolean? = null,

    @Json(name = "free_provider")
    val freeProvider: kotlin.Boolean? = null,

    @Json(name = "suppression_match")
    val suppressionMatch: ValidationResponseSuppressionMatch? = null

) {

    /**
     * Validation status
     *
     * Values: valid,invalid,catch_all,do_not_mail,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "valid") valid("valid"),
        @Json(name = "invalid") invalid("invalid"),
        @Json(name = "catch_all") catch_all("catch_all"),
        @Json(name = "do_not_mail") do_not_mail("do_not_mail"),
        @Json(name = "unknown") unknown("unknown");
    }
    /**
     * Recommended action
     *
     * Values: accept,accept_with_caution,reject,retry_later
     */
    @JsonClass(generateAdapter = false)
    enum class Action(val value: kotlin.String) {
        @Json(name = "accept") accept("accept"),
        @Json(name = "accept_with_caution") accept_with_caution("accept_with_caution"),
        @Json(name = "reject") reject("reject"),
        @Json(name = "retry_later") retry_later("retry_later");
    }

}

