/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AddPolicyRule201Response
import org.openapitools.client.models.PolicyRule

class AddPolicyRule201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddPolicyRule201Response
        //val modelInstance = AddPolicyRule201Response()

        // to test the property `rule`
        should("test rule") {
            // uncomment below to test the property
            //modelInstance.rule shouldBe ("TODO")
        }

    }
}
