/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateJobFromS3Request

class CreateJobFromS3RequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateJobFromS3Request
        //val modelInstance = CreateJobFromS3Request()

        // to test the property `s3Key` - S3 key from presigned upload
        should("test s3Key") {
            // uncomment below to test the property
            //modelInstance.s3Key shouldBe ("TODO")
        }

        // to test the property `dedup`
        should("test dedup") {
            // uncomment below to test the property
            //modelInstance.dedup shouldBe ("TODO")
        }

    }
}
