/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ErrorResponse

class ErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorResponse
        //val modelInstance = ErrorResponse()

        // to test the property `error` - Machine-readable error code
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `message` - Human-readable error message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
