/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Pagination

class PaginationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Pagination
        //val modelInstance = Pagination()

        // to test the property `page`
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `perPage`
        should("test perPage") {
            // uncomment below to test the property
            //modelInstance.perPage shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `totalPages`
        should("test totalPages") {
            // uncomment below to test the property
            //modelInstance.totalPages shouldBe ("TODO")
        }

    }
}
