/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PolicyListResponseLimits

class PolicyListResponseLimitsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyListResponseLimits
        //val modelInstance = PolicyListResponseLimits()

        // to test the property `maxPolicies` - -1 means unlimited
        should("test maxPolicies") {
            // uncomment below to test the property
            //modelInstance.maxPolicies shouldBe ("TODO")
        }

        // to test the property `maxRulesPerPolicy`
        should("test maxRulesPerPolicy") {
            // uncomment below to test the property
            //modelInstance.maxRulesPerPolicy shouldBe ("TODO")
        }

        // to test the property `plan`
        should("test plan") {
            // uncomment below to test the property
            //modelInstance.plan shouldBe ("TODO")
        }

    }
}
