/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PolicyPresetsResponse
import org.openapitools.client.models.PolicyPresetsResponsePresetsInner

class PolicyPresetsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyPresetsResponse
        //val modelInstance = PolicyPresetsResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `presets`
        should("test presets") {
            // uncomment below to test the property
            //modelInstance.presets shouldBe ("TODO")
        }

    }
}
