/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PolicyTestResponse

class PolicyTestResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyTestResponse
        //val modelInstance = PolicyTestResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `original` - Original validation result before policy
        should("test original") {
            // uncomment below to test the property
            //modelInstance.original shouldBe ("TODO")
        }

        // to test the property `modified` - Result after policy applied
        should("test modified") {
            // uncomment below to test the property
            //modelInstance.modified shouldBe ("TODO")
        }

        // to test the property `matchedRule` - The rule that matched, or null if none matched
        should("test matchedRule") {
            // uncomment below to test the property
            //modelInstance.matchedRule shouldBe ("TODO")
        }

        // to test the property `rulesEvaluated`
        should("test rulesEvaluated") {
            // uncomment below to test the property
            //modelInstance.rulesEvaluated shouldBe ("TODO")
        }

    }
}
