/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PolicyResponse
import org.openapitools.client.models.Policy

class PolicyResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyResponse
        //val modelInstance = PolicyResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `policy`
        should("test policy") {
            // uncomment below to test the property
            //modelInstance.policy shouldBe ("TODO")
        }

    }
}
