/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PolicyRule
import org.openapitools.client.models.PolicyRuleAction

class PolicyRuleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyRule
        //val modelInstance = PolicyRule()

        // to test the property `type` - Rule type determines how condition is evaluated
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `condition` - Condition depends on rule type. status_override: {status}, domain_filter: {domain_mode, domains}, check_requirement: {check, required}, sub_status_override: {sub_status}
        should("test condition") {
            // uncomment below to test the property
            //modelInstance.condition shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `sequence`
        should("test sequence") {
            // uncomment below to test the property
            //modelInstance.sequence shouldBe ("TODO")
        }

        // to test the property `isEnabled`
        should("test isEnabled") {
            // uncomment below to test the property
            //modelInstance.isEnabled shouldBe ("TODO")
        }

    }
}
