/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TelemetrySummary
import org.openapitools.client.models.TelemetrySummaryRates
import org.openapitools.client.models.TelemetrySummaryTopDomainsInner
import org.openapitools.client.models.TelemetrySummaryTopReasonsInner
import org.openapitools.client.models.TelemetrySummaryTotals

class TelemetrySummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetrySummary
        //val modelInstance = TelemetrySummary()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `window`
        should("test window") {
            // uncomment below to test the property
            //modelInstance.window shouldBe ("TODO")
        }

        // to test the property `generatedAt`
        should("test generatedAt") {
            // uncomment below to test the property
            //modelInstance.generatedAt shouldBe ("TODO")
        }

        // to test the property `timezone`
        should("test timezone") {
            // uncomment below to test the property
            //modelInstance.timezone shouldBe ("TODO")
        }

        // to test the property `totals`
        should("test totals") {
            // uncomment below to test the property
            //modelInstance.totals shouldBe ("TODO")
        }

        // to test the property `rates`
        should("test rates") {
            // uncomment below to test the property
            //modelInstance.rates shouldBe ("TODO")
        }

        // to test the property `topReasons` - Top rejection/status reasons
        should("test topReasons") {
            // uncomment below to test the property
            //modelInstance.topReasons shouldBe ("TODO")
        }

        // to test the property `topDomains` - Top domains by volume
        should("test topDomains") {
            // uncomment below to test the property
            //modelInstance.topDomains shouldBe ("TODO")
        }

    }
}
