/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TelemetrySummaryTopDomainsInner

class TelemetrySummaryTopDomainsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetrySummaryTopDomainsInner
        //val modelInstance = TelemetrySummaryTopDomainsInner()

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `volume`
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

        // to test the property `deliverable`
        should("test deliverable") {
            // uncomment below to test the property
            //modelInstance.deliverable shouldBe ("TODO")
        }

        // to test the property `reject`
        should("test reject") {
            // uncomment below to test the property
            //modelInstance.reject shouldBe ("TODO")
        }

        // to test the property `unknown`
        should("test unknown") {
            // uncomment below to test the property
            //modelInstance.unknown shouldBe ("TODO")
        }

        // to test the property `catchAll`
        should("test catchAll") {
            // uncomment below to test the property
            //modelInstance.catchAll shouldBe ("TODO")
        }

    }
}
