/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TestPolicyRequest
import org.openapitools.client.models.TestPolicyRequestTestResult

class TestPolicyRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestPolicyRequest
        //val modelInstance = TestPolicyRequest()

        // to test the property `policyId`
        should("test policyId") {
            // uncomment below to test the property
            //modelInstance.policyId shouldBe ("TODO")
        }

        // to test the property `testResult`
        should("test testResult") {
            // uncomment below to test the property
            //modelInstance.testResult shouldBe ("TODO")
        }

    }
}
