/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidateBatchRequest

class ValidateBatchRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidateBatchRequest
        //val modelInstance = ValidateBatchRequest()

        // to test the property `emails` - List of emails to validate
        should("test emails") {
            // uncomment below to test the property
            //modelInstance.emails shouldBe ("TODO")
        }

        // to test the property `depth`
        should("test depth") {
            // uncomment below to test the property
            //modelInstance.depth shouldBe ("TODO")
        }

        // to test the property `policyId` - Optional policy ID
        should("test policyId") {
            // uncomment below to test the property
            //modelInstance.policyId shouldBe ("TODO")
        }

    }
}
