/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidateBatch200ResponseSummary

class ValidateBatch200ResponseSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidateBatch200ResponseSummary
        //val modelInstance = ValidateBatch200ResponseSummary()

        // to test the property `valid`
        should("test valid") {
            // uncomment below to test the property
            //modelInstance.valid shouldBe ("TODO")
        }

        // to test the property `invalid`
        should("test invalid") {
            // uncomment below to test the property
            //modelInstance.invalid shouldBe ("TODO")
        }

        // to test the property `catchAll`
        should("test catchAll") {
            // uncomment below to test the property
            //modelInstance.catchAll shouldBe ("TODO")
        }

        // to test the property `unknown`
        should("test unknown") {
            // uncomment below to test the property
            //modelInstance.unknown shouldBe ("TODO")
        }

        // to test the property `doNotMail`
        should("test doNotMail") {
            // uncomment below to test the property
            //modelInstance.doNotMail shouldBe ("TODO")
        }

    }
}
