/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidationResponse
import org.openapitools.client.models.ValidationResponsePolicyApplied
import org.openapitools.client.models.ValidationResponseSuppressionMatch

class ValidationResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationResponse
        //val modelInstance = ValidationResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `status` - Validation status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `action` - Recommended action
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `mxFound` - Whether MX records were found for the domain
        should("test mxFound") {
            // uncomment below to test the property
            //modelInstance.mxFound shouldBe ("TODO")
        }

        // to test the property `disposable` - Whether domain is a known disposable email provider
        should("test disposable") {
            // uncomment below to test the property
            //modelInstance.disposable shouldBe ("TODO")
        }

        // to test the property `roleAccount` - Whether address is a role account (e.g., info@, admin@)
        should("test roleAccount") {
            // uncomment below to test the property
            //modelInstance.roleAccount shouldBe ("TODO")
        }

        // to test the property `freeProvider` - Whether domain is a known free email provider (e.g., gmail.com)
        should("test freeProvider") {
            // uncomment below to test the property
            //modelInstance.freeProvider shouldBe ("TODO")
        }

        // to test the property `depth` - Validation depth used for this check
        should("test depth") {
            // uncomment below to test the property
            //modelInstance.depth shouldBe ("TODO")
        }

        // to test the property `processedAt` - ISO 8601 timestamp of validation
        should("test processedAt") {
            // uncomment below to test the property
            //modelInstance.processedAt shouldBe ("TODO")
        }

        // to test the property `subStatus` - Detailed status reason. Omitted when none.
        should("test subStatus") {
            // uncomment below to test the property
            //modelInstance.subStatus shouldBe ("TODO")
        }

        // to test the property `mxHost` - Primary MX hostname. Omitted when MX not resolved.
        should("test mxHost") {
            // uncomment below to test the property
            //modelInstance.mxHost shouldBe ("TODO")
        }

        // to test the property `smtpCheck` - Whether SMTP verification passed. Omitted when SMTP not checked.
        should("test smtpCheck") {
            // uncomment below to test the property
            //modelInstance.smtpCheck shouldBe ("TODO")
        }

        // to test the property `catchAll` - Whether domain is catch-all. Omitted when SMTP not checked.
        should("test catchAll") {
            // uncomment below to test the property
            //modelInstance.catchAll shouldBe ("TODO")
        }

        // to test the property `suggestedEmail` - Typo correction suggestion. Omitted when no typo detected.
        should("test suggestedEmail") {
            // uncomment below to test the property
            //modelInstance.suggestedEmail shouldBe ("TODO")
        }

        // to test the property `retryAfterMs` - Suggested retry delay in milliseconds. Present only for retry_later action.
        should("test retryAfterMs") {
            // uncomment below to test the property
            //modelInstance.retryAfterMs shouldBe ("TODO")
        }

        // to test the property `suppressionMatch`
        should("test suppressionMatch") {
            // uncomment below to test the property
            //modelInstance.suppressionMatch shouldBe ("TODO")
        }

        // to test the property `policyApplied`
        should("test policyApplied") {
            // uncomment below to test the property
            //modelInstance.policyApplied shouldBe ("TODO")
        }

    }
}
