/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidateRequest

class ValidateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidateRequest
        //val modelInstance = ValidateRequest()

        // to test the property `email` - Email address to validate
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `depth` - Validation depth. 'standard' skips SMTP verification.
        should("test depth") {
            // uncomment below to test the property
            //modelInstance.depth shouldBe ("TODO")
        }

        // to test the property `policyId` - Optional policy ID to use instead of default policy
        should("test policyId") {
            // uncomment below to test the property
            //modelInstance.policyId shouldBe ("TODO")
        }

    }
}
