/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ValidationResponseSuppressionMatch

class ValidationResponseSuppressionMatchTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationResponseSuppressionMatch
        //val modelInstance = ValidationResponseSuppressionMatch()

        // to test the property `matchType`
        should("test matchType") {
            // uncomment below to test the property
            //modelInstance.matchType shouldBe ("TODO")
        }

        // to test the property `matchValue`
        should("test matchValue") {
            // uncomment below to test the property
            //modelInstance.matchValue shouldBe ("TODO")
        }

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

    }
}
