/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.BulkValidationApi
import org.openapitools.client.models.CreateJobFromS3Request
import org.openapitools.client.models.CreateJobRequest
import org.openapitools.client.models.DeleteJob200Response
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.GetPresignedUploadRequest
import org.openapitools.client.models.JobListResponse
import org.openapitools.client.models.JobResponse
import org.openapitools.client.models.PresignedUploadResponse
import org.openapitools.client.models.ResultsResponse

class BulkValidationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BulkValidationApi
        //val apiInstance = BulkValidationApi()

        // to test cancelJob
        should("test cancelJob") {
            // uncomment below to test cancelJob
            //val jobId : kotlin.String = jobId_example // kotlin.String | 
            //val result : JobResponse = apiInstance.cancelJob(jobId)
            //result shouldBe ("TODO")
        }

        // to test createJob
        should("test createJob") {
            // uncomment below to test createJob
            //val createJobRequest : CreateJobRequest =  // CreateJobRequest | 
            //val result : JobResponse = apiInstance.createJob(createJobRequest)
            //result shouldBe ("TODO")
        }

        // to test createJobFromS3
        should("test createJobFromS3") {
            // uncomment below to test createJobFromS3
            //val createJobFromS3Request : CreateJobFromS3Request =  // CreateJobFromS3Request | 
            //val result : JobResponse = apiInstance.createJobFromS3(createJobFromS3Request)
            //result shouldBe ("TODO")
        }

        // to test createJobUpload
        should("test createJobUpload") {
            // uncomment below to test createJobUpload
            //val file : java.io.File = BINARY_DATA_HERE // java.io.File | CSV, Excel (.xlsx, .xls), ODS, or TXT file
            //val dedup : kotlin.Boolean = true // kotlin.Boolean | Remove duplicate emails
            //val metadata : kotlin.String = metadata_example // kotlin.String | JSON metadata for the job
            //val result : JobResponse = apiInstance.createJobUpload(file, dedup, metadata)
            //result shouldBe ("TODO")
        }

        // to test deleteJob
        should("test deleteJob") {
            // uncomment below to test deleteJob
            //val jobId : kotlin.String = jobId_example // kotlin.String | 
            //val result : DeleteJob200Response = apiInstance.deleteJob(jobId)
            //result shouldBe ("TODO")
        }

        // to test getJob
        should("test getJob") {
            // uncomment below to test getJob
            //val jobId : kotlin.String = jobId_example // kotlin.String | 
            //val result : JobResponse = apiInstance.getJob(jobId)
            //result shouldBe ("TODO")
        }

        // to test getJobResults
        should("test getJobResults") {
            // uncomment below to test getJobResults
            //val jobId : kotlin.String = jobId_example // kotlin.String | 
            //val format : kotlin.String = format_example // kotlin.String | 
            //val filter : kotlin.String = filter_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val result : ResultsResponse = apiInstance.getJobResults(jobId, format, filter, page, perPage)
            //result shouldBe ("TODO")
        }

        // to test getPresignedUpload
        should("test getPresignedUpload") {
            // uncomment below to test getPresignedUpload
            //val getPresignedUploadRequest : GetPresignedUploadRequest =  // GetPresignedUploadRequest | 
            //val result : PresignedUploadResponse = apiInstance.getPresignedUpload(getPresignedUploadRequest)
            //result shouldBe ("TODO")
        }

        // to test listJobs
        should("test listJobs") {
            // uncomment below to test listJobs
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val status : kotlin.String = status_example // kotlin.String | 
            //val result : JobListResponse = apiInstance.listJobs(page, perPage, status)
            //result shouldBe ("TODO")
        }

    }
}
