/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.EmailValidationApi
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.ValidateBatch200Response
import org.openapitools.client.models.ValidateBatchRequest
import org.openapitools.client.models.ValidateRequest
import org.openapitools.client.models.ValidationResponse

class EmailValidationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmailValidationApi
        //val apiInstance = EmailValidationApi()

        // to test validateBatch
        should("test validateBatch") {
            // uncomment below to test validateBatch
            //val validateBatchRequest : ValidateBatchRequest =  // ValidateBatchRequest | 
            //val result : ValidateBatch200Response = apiInstance.validateBatch(validateBatchRequest)
            //result shouldBe ("TODO")
        }

        // to test validateEmail
        should("test validateEmail") {
            // uncomment below to test validateEmail
            //val validateRequest : ValidateRequest =  // ValidateRequest | 
            //val result : ValidationResponse = apiInstance.validateEmail(validateRequest)
            //result shouldBe ("TODO")
        }

    }
}
