/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SuppressionListsApi
import org.openapitools.client.models.AddSuppressionRequest
import org.openapitools.client.models.AddSuppressionResponse
import org.openapitools.client.models.CheckSuppressionRequest
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.RemoveSuppression200Response
import org.openapitools.client.models.RemoveSuppressionRequest
import org.openapitools.client.models.SuppressionCheckResponse
import org.openapitools.client.models.SuppressionListResponse
import org.openapitools.client.models.SuppressionStatsResponse

class SuppressionListsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuppressionListsApi
        //val apiInstance = SuppressionListsApi()

        // to test addSuppression
        should("test addSuppression") {
            // uncomment below to test addSuppression
            //val addSuppressionRequest : AddSuppressionRequest =  // AddSuppressionRequest | 
            //val result : AddSuppressionResponse = apiInstance.addSuppression(addSuppressionRequest)
            //result shouldBe ("TODO")
        }

        // to test checkSuppression
        should("test checkSuppression") {
            // uncomment below to test checkSuppression
            //val checkSuppressionRequest : CheckSuppressionRequest =  // CheckSuppressionRequest | 
            //val result : SuppressionCheckResponse = apiInstance.checkSuppression(checkSuppressionRequest)
            //result shouldBe ("TODO")
        }

        // to test getSuppressionStats
        should("test getSuppressionStats") {
            // uncomment below to test getSuppressionStats
            //val result : SuppressionStatsResponse = apiInstance.getSuppressionStats()
            //result shouldBe ("TODO")
        }

        // to test listSuppression
        should("test listSuppression") {
            // uncomment below to test listSuppression
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val type : kotlin.String = type_example // kotlin.String | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val result : SuppressionListResponse = apiInstance.listSuppression(page, perPage, type, search)
            //result shouldBe ("TODO")
        }

        // to test removeSuppression
        should("test removeSuppression") {
            // uncomment below to test removeSuppression
            //val removeSuppressionRequest : RemoveSuppressionRequest =  // RemoveSuppressionRequest | 
            //val result : RemoveSuppression200Response = apiInstance.removeSuppression(removeSuppressionRequest)
            //result shouldBe ("TODO")
        }

    }
}
