/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SystemApi
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.HealthCheck200Response
import org.openapitools.client.models.TelemetrySummary

class SystemApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemApi
        //val apiInstance = SystemApi()

        // to test getTelemetrySummary
        should("test getTelemetrySummary") {
            // uncomment below to test getTelemetrySummary
            //val window : kotlin.String = window_example // kotlin.String | Time window for metrics
            //val result : TelemetrySummary = apiInstance.getTelemetrySummary(window)
            //result shouldBe ("TODO")
        }

        // to test healthCheck
        should("test healthCheck") {
            // uncomment below to test healthCheck
            //val result : HealthCheck200Response = apiInstance.healthCheck()
            //result shouldBe ("TODO")
        }

    }
}
