/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ValidationPoliciesApi
import org.openapitools.client.models.AddPolicyRule201Response
import org.openapitools.client.models.CreatePolicyFromPresetRequest
import org.openapitools.client.models.CreatePolicyRequest
import org.openapitools.client.models.DeletePolicy200Response
import org.openapitools.client.models.DeletePolicyRule200Response
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.PolicyListResponse
import org.openapitools.client.models.PolicyPresetsResponse
import org.openapitools.client.models.PolicyResponse
import org.openapitools.client.models.PolicyRule
import org.openapitools.client.models.PolicyTestResponse
import org.openapitools.client.models.TestPolicyRequest
import org.openapitools.client.models.UpdatePolicyRequest

class ValidationPoliciesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationPoliciesApi
        //val apiInstance = ValidationPoliciesApi()

        // to test addPolicyRule
        should("test addPolicyRule") {
            // uncomment below to test addPolicyRule
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val policyRule : PolicyRule =  // PolicyRule | 
            //val result : AddPolicyRule201Response = apiInstance.addPolicyRule(policyId, policyRule)
            //result shouldBe ("TODO")
        }

        // to test createPolicy
        should("test createPolicy") {
            // uncomment below to test createPolicy
            //val createPolicyRequest : CreatePolicyRequest =  // CreatePolicyRequest | 
            //val result : PolicyResponse = apiInstance.createPolicy(createPolicyRequest)
            //result shouldBe ("TODO")
        }

        // to test createPolicyFromPreset
        should("test createPolicyFromPreset") {
            // uncomment below to test createPolicyFromPreset
            //val createPolicyFromPresetRequest : CreatePolicyFromPresetRequest =  // CreatePolicyFromPresetRequest | 
            //val result : PolicyResponse = apiInstance.createPolicyFromPreset(createPolicyFromPresetRequest)
            //result shouldBe ("TODO")
        }

        // to test deletePolicy
        should("test deletePolicy") {
            // uncomment below to test deletePolicy
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val result : DeletePolicy200Response = apiInstance.deletePolicy(policyId)
            //result shouldBe ("TODO")
        }

        // to test deletePolicyRule
        should("test deletePolicyRule") {
            // uncomment below to test deletePolicyRule
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val ruleId : kotlin.Int = 56 // kotlin.Int | 
            //val result : DeletePolicyRule200Response = apiInstance.deletePolicyRule(policyId, ruleId)
            //result shouldBe ("TODO")
        }

        // to test getPolicy
        should("test getPolicy") {
            // uncomment below to test getPolicy
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val result : PolicyResponse = apiInstance.getPolicy(policyId)
            //result shouldBe ("TODO")
        }

        // to test getPolicyPresets
        should("test getPolicyPresets") {
            // uncomment below to test getPolicyPresets
            //val result : PolicyPresetsResponse = apiInstance.getPolicyPresets()
            //result shouldBe ("TODO")
        }

        // to test listPolicies
        should("test listPolicies") {
            // uncomment below to test listPolicies
            //val includeRules : kotlin.Boolean = true // kotlin.Boolean | Include full rules in response
            //val result : PolicyListResponse = apiInstance.listPolicies(includeRules)
            //result shouldBe ("TODO")
        }

        // to test testPolicy
        should("test testPolicy") {
            // uncomment below to test testPolicy
            //val testPolicyRequest : TestPolicyRequest =  // TestPolicyRequest | 
            //val result : PolicyTestResponse = apiInstance.testPolicy(testPolicyRequest)
            //result shouldBe ("TODO")
        }

        // to test updatePolicy
        should("test updatePolicy") {
            // uncomment below to test updatePolicy
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val updatePolicyRequest : UpdatePolicyRequest =  // UpdatePolicyRequest | 
            //val result : PolicyResponse = apiInstance.updatePolicy(policyId, updatePolicyRequest)
            //result shouldBe ("TODO")
        }

    }
}
