/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.apis.EmailValidationApi
import com.mailodds.models.ErrorResponse
import com.mailodds.models.ValidateRequest
import com.mailodds.models.ValidationResponse

class EmailValidationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmailValidationApi
        //val apiInstance = EmailValidationApi()

        // to test validateEmail
        should("test validateEmail") {
            // uncomment below to test validateEmail
            //val validateRequest : ValidateRequest =  // ValidateRequest | 
            //val result : ValidationResponse = apiInstance.validateEmail(validateRequest)
            //result shouldBe ("TODO")
        }

    }
}
