/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.apis.ValidationPoliciesApi
import com.mailodds.models.AddPolicyRule201Response
import com.mailodds.models.CreatePolicyFromPresetRequest
import com.mailodds.models.CreatePolicyRequest
import com.mailodds.models.DeletePolicy200Response
import com.mailodds.models.DeletePolicyRule200Response
import com.mailodds.models.ErrorResponse
import com.mailodds.models.PolicyListResponse
import com.mailodds.models.PolicyPresetsResponse
import com.mailodds.models.PolicyResponse
import com.mailodds.models.PolicyRule
import com.mailodds.models.PolicyTestResponse
import com.mailodds.models.TestPolicyRequest
import com.mailodds.models.UpdatePolicyRequest

class ValidationPoliciesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationPoliciesApi
        //val apiInstance = ValidationPoliciesApi()

        // to test addPolicyRule
        should("test addPolicyRule") {
            // uncomment below to test addPolicyRule
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val policyRule : PolicyRule =  // PolicyRule | 
            //val result : AddPolicyRule201Response = apiInstance.addPolicyRule(policyId, policyRule)
            //result shouldBe ("TODO")
        }

        // to test createPolicy
        should("test createPolicy") {
            // uncomment below to test createPolicy
            //val createPolicyRequest : CreatePolicyRequest =  // CreatePolicyRequest | 
            //val result : PolicyResponse = apiInstance.createPolicy(createPolicyRequest)
            //result shouldBe ("TODO")
        }

        // to test createPolicyFromPreset
        should("test createPolicyFromPreset") {
            // uncomment below to test createPolicyFromPreset
            //val createPolicyFromPresetRequest : CreatePolicyFromPresetRequest =  // CreatePolicyFromPresetRequest | 
            //val result : PolicyResponse = apiInstance.createPolicyFromPreset(createPolicyFromPresetRequest)
            //result shouldBe ("TODO")
        }

        // to test deletePolicy
        should("test deletePolicy") {
            // uncomment below to test deletePolicy
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val result : DeletePolicy200Response = apiInstance.deletePolicy(policyId)
            //result shouldBe ("TODO")
        }

        // to test deletePolicyRule
        should("test deletePolicyRule") {
            // uncomment below to test deletePolicyRule
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val ruleId : kotlin.Int = 56 // kotlin.Int | 
            //val result : DeletePolicyRule200Response = apiInstance.deletePolicyRule(policyId, ruleId)
            //result shouldBe ("TODO")
        }

        // to test getPolicy
        should("test getPolicy") {
            // uncomment below to test getPolicy
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val result : PolicyResponse = apiInstance.getPolicy(policyId)
            //result shouldBe ("TODO")
        }

        // to test getPolicyPresets
        should("test getPolicyPresets") {
            // uncomment below to test getPolicyPresets
            //val result : PolicyPresetsResponse = apiInstance.getPolicyPresets()
            //result shouldBe ("TODO")
        }

        // to test listPolicies
        should("test listPolicies") {
            // uncomment below to test listPolicies
            //val includeRules : kotlin.Boolean = true // kotlin.Boolean | Include full rules in response
            //val result : PolicyListResponse = apiInstance.listPolicies(includeRules)
            //result shouldBe ("TODO")
        }

        // to test testPolicy
        should("test testPolicy") {
            // uncomment below to test testPolicy
            //val testPolicyRequest : TestPolicyRequest =  // TestPolicyRequest | 
            //val result : PolicyTestResponse = apiInstance.testPolicy(testPolicyRequest)
            //result shouldBe ("TODO")
        }

        // to test updatePolicy
        should("test updatePolicy") {
            // uncomment below to test updatePolicy
            //val policyId : kotlin.Int = 56 // kotlin.Int | 
            //val updatePolicyRequest : UpdatePolicyRequest =  // UpdatePolicyRequest | 
            //val result : PolicyResponse = apiInstance.updatePolicy(policyId, updatePolicyRequest)
            //result shouldBe ("TODO")
        }

    }
}
