/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.mailodds.models.ErrorResponse
import com.mailodds.models.ValidateRequest
import com.mailodds.models.ValidationResponse

import com.squareup.moshi.Json

import com.mailodds.infrastructure.ApiClient
import com.mailodds.infrastructure.ApiResponse
import com.mailodds.infrastructure.ClientException
import com.mailodds.infrastructure.ClientError
import com.mailodds.infrastructure.ServerException
import com.mailodds.infrastructure.ServerError
import com.mailodds.infrastructure.MultiValueMap
import com.mailodds.infrastructure.PartConfig
import com.mailodds.infrastructure.RequestConfig
import com.mailodds.infrastructure.RequestMethod
import com.mailodds.infrastructure.ResponseType
import com.mailodds.infrastructure.Success
import com.mailodds.infrastructure.toMultiValue

open class EmailValidationApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.mailodds.com/v1")
        }
    }

    /**
     * POST /v1/validate
     * Validate single email
     * Validate a single email address. Returns detailed validation results including status, sub-status, and recommended action.
     * @param validateRequest 
     * @return ValidationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun validateEmail(validateRequest: ValidateRequest) : ValidationResponse {
        val localVarResponse = validateEmailWithHttpInfo(validateRequest = validateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ValidationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/validate
     * Validate single email
     * Validate a single email address. Returns detailed validation results including status, sub-status, and recommended action.
     * @param validateRequest 
     * @return ApiResponse<ValidationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun validateEmailWithHttpInfo(validateRequest: ValidateRequest) : ApiResponse<ValidationResponse?> {
        val localVariableConfig = validateEmailRequestConfig(validateRequest = validateRequest)

        return request<ValidateRequest, ValidationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation validateEmail
     *
     * @param validateRequest 
     * @return RequestConfig
     */
    fun validateEmailRequestConfig(validateRequest: ValidateRequest) : RequestConfig<ValidateRequest> {
        val localVariableBody = validateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/validate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
