/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param `value` 
 * @param reason 
 */


data class AddSuppressionRequestEntriesInner (

    @Json(name = "type")
    val type: AddSuppressionRequestEntriesInner.Type,

    @Json(name = "value")
    val `value`: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: email,domain
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "email") email("email"),
        @Json(name = "domain") domain("domain");
    }

}

