/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param presetId 
 * @param name 
 * @param isDefault 
 */


data class CreatePolicyFromPresetRequest (

    @Json(name = "preset_id")
    val presetId: CreatePolicyFromPresetRequest.PresetId,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "is_default")
    val isDefault: kotlin.Boolean? = false

) {

    /**
     * 
     *
     * Values: strict,permissive,smtp_required
     */
    @JsonClass(generateAdapter = false)
    enum class PresetId(val value: kotlin.String) {
        @Json(name = "strict") strict("strict"),
        @Json(name = "permissive") permissive("permissive"),
        @Json(name = "smtp_required") smtp_required("smtp_required");
    }

}

