/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filename Original filename
 * @param contentType File MIME type
 */


data class GetPresignedUploadRequest (

    /* Original filename */
    @Json(name = "filename")
    val filename: kotlin.String,

    /* File MIME type */
    @Json(name = "content_type")
    val contentType: kotlin.String? = null

) {


}

