/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.JobSummary

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param status 
 * @param totalCount 
 * @param processedCount 
 * @param progressPercent 
 * @param summary 
 * @param createdAt 
 * @param completedAt 
 * @param metadata 
 */


data class Job (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "status")
    val status: Job.Status? = null,

    @Json(name = "total_count")
    val totalCount: kotlin.Int? = null,

    @Json(name = "processed_count")
    val processedCount: kotlin.Int? = null,

    @Json(name = "progress_percent")
    val progressPercent: kotlin.Int? = null,

    @Json(name = "summary")
    val summary: JobSummary? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @Json(name = "metadata")
    val metadata: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: pending,processing,completed,failed,cancelled
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending"),
        @Json(name = "processing") processing("processing"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "cancelled") cancelled("cancelled");
    }

}

