/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Job

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param job 
 */


data class JobResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "job")
    val job: Job? = null

) {


}

