/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page 
 * @param perPage 
 * @param total 
 * @param totalPages 
 */


data class Pagination (

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "per_page")
    val perPage: kotlin.Int? = null,

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "total_pages")
    val totalPages: kotlin.Int? = null

) {


}

