/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PolicyRule

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param isDefault 
 * @param isEnabled 
 * @param priority 
 * @param ruleCount 
 * @param rules 
 * @param createdAt 
 */


data class Policy (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "is_default")
    val isDefault: kotlin.Boolean? = null,

    @Json(name = "is_enabled")
    val isEnabled: kotlin.Boolean? = null,

    @Json(name = "priority")
    val priority: kotlin.Int? = null,

    @Json(name = "rule_count")
    val ruleCount: kotlin.Int? = null,

    @Json(name = "rules")
    val rules: kotlin.collections.List<PolicyRule>? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

