/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url 
 * @param fields 
 * @param s3Key 
 * @param expiresIn 
 */


data class PresignedUploadResponseUpload (

    @Json(name = "url")
    val url: java.net.URI? = null,

    @Json(name = "fields")
    val fields: kotlin.Any? = null,

    @Json(name = "s3_key")
    val s3Key: kotlin.String? = null,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int? = null

) {


}

