/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Pagination
import org.openapitools.client.models.ValidationResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param results 
 * @param pagination 
 */


data class ResultsResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<ValidationResult>? = null,

    @Json(name = "pagination")
    val pagination: Pagination? = null

) {


}

