/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param email 
 * @param suppressed 
 * @param matchType 
 * @param matchValue 
 */


data class SuppressionCheckResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "suppressed")
    val suppressed: kotlin.Boolean? = null,

    @Json(name = "match_type")
    val matchType: SuppressionCheckResponse.MatchType? = null,

    @Json(name = "match_value")
    val matchValue: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: email,domain
     */
    @JsonClass(generateAdapter = false)
    enum class MatchType(val value: kotlin.String) {
        @Json(name = "email") email("email"),
        @Json(name = "domain") domain("domain");
    }

}

