/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TelemetrySummaryRates
import org.openapitools.client.models.TelemetrySummaryTopDomainsInner
import org.openapitools.client.models.TelemetrySummaryTopReasonsInner
import org.openapitools.client.models.TelemetrySummaryTotals

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Validation metrics for building dashboards and monitoring.
 *
 * @param schemaVersion 
 * @param window 
 * @param generatedAt 
 * @param timezone 
 * @param totals 
 * @param rates 
 * @param topReasons Top rejection/status reasons
 * @param topDomains Top domains by volume
 */


data class TelemetrySummary (

    @Json(name = "schemaVersion")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "window")
    val window: TelemetrySummary.Window? = null,

    @Json(name = "generatedAt")
    val generatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "timezone")
    val timezone: kotlin.String? = null,

    @Json(name = "totals")
    val totals: TelemetrySummaryTotals? = null,

    @Json(name = "rates")
    val rates: TelemetrySummaryRates? = null,

    /* Top rejection/status reasons */
    @Json(name = "topReasons")
    val topReasons: kotlin.collections.List<TelemetrySummaryTopReasonsInner>? = null,

    /* Top domains by volume */
    @Json(name = "topDomains")
    val topDomains: kotlin.collections.List<TelemetrySummaryTopDomainsInner>? = null

) {

    /**
     * 
     *
     * Values: _1h,_24h,_30d
     */
    @JsonClass(generateAdapter = false)
    enum class Window(val value: kotlin.String) {
        @Json(name = "1h") _1h("1h"),
        @Json(name = "24h") _24h("24h"),
        @Json(name = "30d") _30d("30d");
    }

}

