/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Status distribution as decimals (0-1)
 *
 * @param deliverable Rate of valid + catch_all emails
 * @param reject Rate of invalid + do_not_mail emails
 * @param unknown Rate of unknown status
 * @param suppressed Rate of suppressed emails
 */


data class TelemetrySummaryRates (

    /* Rate of valid + catch_all emails */
    @Json(name = "deliverable")
    val deliverable: java.math.BigDecimal? = null,

    /* Rate of invalid + do_not_mail emails */
    @Json(name = "reject")
    val reject: java.math.BigDecimal? = null,

    /* Rate of unknown status */
    @Json(name = "unknown")
    val unknown: java.math.BigDecimal? = null,

    /* Rate of suppressed emails */
    @Json(name = "suppressed")
    val suppressed: java.math.BigDecimal? = null

) {


}

