/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TestPolicyRequestTestResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param policyId 
 * @param testResult 
 */


data class TestPolicyRequest (

    @Json(name = "policy_id")
    val policyId: kotlin.Int,

    @Json(name = "test_result")
    val testResult: TestPolicyRequestTestResult

) {


}

