/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email Email address to validate
 * @param depth Validation depth. 'standard' skips SMTP verification.
 * @param policyId Optional policy ID to use instead of default policy
 */


data class ValidateRequest (

    /* Email address to validate */
    @Json(name = "email")
    val email: kotlin.String,

    /* Validation depth. 'standard' skips SMTP verification. */
    @Json(name = "depth")
    val depth: ValidateRequest.Depth? = Depth.enhanced,

    /* Optional policy ID to use instead of default policy */
    @Json(name = "policy_id")
    val policyId: kotlin.Int? = null

) {

    /**
     * Validation depth. 'standard' skips SMTP verification.
     *
     * Values: standard,enhanced
     */
    @JsonClass(generateAdapter = false)
    enum class Depth(val value: kotlin.String) {
        @Json(name = "standard") standard("standard"),
        @Json(name = "enhanced") enhanced("enhanced");
    }

}

