/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Present when a validation policy modified the result.
 *
 * @param policyId 
 * @param policyName 
 * @param ruleId 
 * @param ruleType 
 */


data class ValidationResponsePolicyApplied (

    @Json(name = "policy_id")
    val policyId: kotlin.Int? = null,

    @Json(name = "policy_name")
    val policyName: kotlin.String? = null,

    @Json(name = "rule_id")
    val ruleId: kotlin.Int? = null,

    @Json(name = "rule_type")
    val ruleType: kotlin.String? = null

) {


}

