/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ValidateBatch200ResponseSummary
import org.openapitools.client.models.ValidationResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param schemaVersion 
 * @param total 
 * @param summary 
 * @param results 
 */


data class ValidateBatch200Response (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String? = null,

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "summary")
    val summary: ValidateBatch200ResponseSummary? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<ValidationResponse>? = null

) {


}

