/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param status 
 * @param subStatus 
 * @param action 
 * @param processedAt 
 */


data class ValidationResult (

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "sub_status")
    val subStatus: kotlin.String? = null,

    @Json(name = "action")
    val action: kotlin.String? = null,

    @Json(name = "processed_at")
    val processedAt: java.time.OffsetDateTime? = null

) {


}

