/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ValidationResponsePolicyApplied
import org.openapitools.client.models.ValidationResponseSuppressionMatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Flat validation response. Conditional fields are omitted (not null) when not applicable.
 *
 * @param schemaVersion 
 * @param email 
 * @param status Validation status
 * @param action Recommended action
 * @param domain 
 * @param mxFound Whether MX records were found for the domain
 * @param disposable Whether domain is a known disposable email provider
 * @param roleAccount Whether address is a role account (e.g., info@, admin@)
 * @param freeProvider Whether domain is a known free email provider (e.g., gmail.com)
 * @param depth Validation depth used for this check
 * @param processedAt ISO 8601 timestamp of validation
 * @param subStatus Detailed status reason. Omitted when none.
 * @param mxHost Primary MX hostname. Omitted when MX not resolved.
 * @param smtpCheck Whether SMTP verification passed. Omitted when SMTP not checked.
 * @param catchAll Whether domain is catch-all. Omitted when SMTP not checked.
 * @param suggestedEmail Typo correction suggestion. Omitted when no typo detected.
 * @param retryAfterMs Suggested retry delay in milliseconds. Present only for retry_later action.
 * @param suppressionMatch 
 * @param policyApplied 
 */


data class ValidationResponse (

    @Json(name = "schema_version")
    val schemaVersion: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    /* Validation status */
    @Json(name = "status")
    val status: ValidationResponse.Status,

    /* Recommended action */
    @Json(name = "action")
    val action: ValidationResponse.Action,

    @Json(name = "domain")
    val domain: kotlin.String,

    /* Whether MX records were found for the domain */
    @Json(name = "mx_found")
    val mxFound: kotlin.Boolean,

    /* Whether domain is a known disposable email provider */
    @Json(name = "disposable")
    val disposable: kotlin.Boolean,

    /* Whether address is a role account (e.g., info@, admin@) */
    @Json(name = "role_account")
    val roleAccount: kotlin.Boolean,

    /* Whether domain is a known free email provider (e.g., gmail.com) */
    @Json(name = "free_provider")
    val freeProvider: kotlin.Boolean,

    /* Validation depth used for this check */
    @Json(name = "depth")
    val depth: ValidationResponse.Depth,

    /* ISO 8601 timestamp of validation */
    @Json(name = "processed_at")
    val processedAt: java.time.OffsetDateTime,

    /* Detailed status reason. Omitted when none. */
    @Json(name = "sub_status")
    val subStatus: ValidationResponse.SubStatus? = null,

    /* Primary MX hostname. Omitted when MX not resolved. */
    @Json(name = "mx_host")
    val mxHost: kotlin.String? = null,

    /* Whether SMTP verification passed. Omitted when SMTP not checked. */
    @Json(name = "smtp_check")
    val smtpCheck: kotlin.Boolean? = null,

    /* Whether domain is catch-all. Omitted when SMTP not checked. */
    @Json(name = "catch_all")
    val catchAll: kotlin.Boolean? = null,

    /* Typo correction suggestion. Omitted when no typo detected. */
    @Json(name = "suggested_email")
    val suggestedEmail: kotlin.String? = null,

    /* Suggested retry delay in milliseconds. Present only for retry_later action. */
    @Json(name = "retry_after_ms")
    val retryAfterMs: kotlin.Int? = null,

    @Json(name = "suppression_match")
    val suppressionMatch: ValidationResponseSuppressionMatch? = null,

    @Json(name = "policy_applied")
    val policyApplied: ValidationResponsePolicyApplied? = null

) {

    /**
     * Validation status
     *
     * Values: valid,invalid,catch_all,do_not_mail,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "valid") valid("valid"),
        @Json(name = "invalid") invalid("invalid"),
        @Json(name = "catch_all") catch_all("catch_all"),
        @Json(name = "do_not_mail") do_not_mail("do_not_mail"),
        @Json(name = "unknown") unknown("unknown");
    }
    /**
     * Recommended action
     *
     * Values: accept,accept_with_caution,reject,retry_later
     */
    @JsonClass(generateAdapter = false)
    enum class Action(val value: kotlin.String) {
        @Json(name = "accept") accept("accept"),
        @Json(name = "accept_with_caution") accept_with_caution("accept_with_caution"),
        @Json(name = "reject") reject("reject"),
        @Json(name = "retry_later") retry_later("retry_later");
    }
    /**
     * Validation depth used for this check
     *
     * Values: standard,enhanced
     */
    @JsonClass(generateAdapter = false)
    enum class Depth(val value: kotlin.String) {
        @Json(name = "standard") standard("standard"),
        @Json(name = "enhanced") enhanced("enhanced");
    }
    /**
     * Detailed status reason. Omitted when none.
     *
     * Values: format_invalid,mx_missing,mx_timeout,smtp_unreachable,smtp_rejected,disposable,role_account,greylisted,catch_all_detected,suppression_match
     */
    @JsonClass(generateAdapter = false)
    enum class SubStatus(val value: kotlin.String) {
        @Json(name = "format_invalid") format_invalid("format_invalid"),
        @Json(name = "mx_missing") mx_missing("mx_missing"),
        @Json(name = "mx_timeout") mx_timeout("mx_timeout"),
        @Json(name = "smtp_unreachable") smtp_unreachable("smtp_unreachable"),
        @Json(name = "smtp_rejected") smtp_rejected("smtp_rejected"),
        @Json(name = "disposable") disposable("disposable"),
        @Json(name = "role_account") role_account("role_account"),
        @Json(name = "greylisted") greylisted("greylisted"),
        @Json(name = "catch_all_detected") catch_all_detected("catch_all_detected"),
        @Json(name = "suppression_match") suppression_match("suppression_match");
    }

}

