/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param valid 
 * @param invalid 
 * @param catchAll 
 * @param unknown 
 * @param doNotMail 
 */


data class ValidateBatch200ResponseSummary (

    @Json(name = "valid")
    val valid: kotlin.Int? = null,

    @Json(name = "invalid")
    val invalid: kotlin.Int? = null,

    @Json(name = "catch_all")
    val catchAll: kotlin.Int? = null,

    @Json(name = "unknown")
    val unknown: kotlin.Int? = null,

    @Json(name = "do_not_mail")
    val doNotMail: kotlin.Int? = null

) {


}

