/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param emails List of emails to validate
 * @param depth 
 * @param policyId Optional policy ID
 */


data class ValidateBatchRequest (

    /* List of emails to validate */
    @Json(name = "emails")
    val emails: kotlin.collections.List<kotlin.String>,

    @Json(name = "depth")
    val depth: ValidateBatchRequest.Depth? = Depth.enhanced,

    /* Optional policy ID */
    @Json(name = "policy_id")
    val policyId: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: standard,enhanced
     */
    @JsonClass(generateAdapter = false)
    enum class Depth(val value: kotlin.String) {
        @Json(name = "standard") standard("standard"),
        @Json(name = "enhanced") enhanced("enhanced");
    }

}

