/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Present only when email matched a suppression list entry.
 *
 * @param matchType 
 * @param matchValue 
 * @param reason 
 */


data class ValidationResponseSuppressionMatch (

    @Json(name = "match_type")
    val matchType: ValidationResponseSuppressionMatch.MatchType? = null,

    @Json(name = "match_value")
    val matchValue: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: email,domain
     */
    @JsonClass(generateAdapter = false)
    enum class MatchType(val value: kotlin.String) {
        @Json(name = "email") email("email"),
        @Json(name = "domain") domain("domain");
    }

}

