/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.AddSuppressionResponse

class AddSuppressionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddSuppressionResponse
        //val modelInstance = AddSuppressionResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `added`
        should("test added") {
            // uncomment below to test the property
            //modelInstance.added shouldBe ("TODO")
        }

        // to test the property `skipped`
        should("test skipped") {
            // uncomment below to test the property
            //modelInstance.skipped shouldBe ("TODO")
        }

    }
}
