/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.CreateJobRequest

class CreateJobRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateJobRequest
        //val modelInstance = CreateJobRequest()

        // to test the property `emails` - List of emails to validate
        should("test emails") {
            // uncomment below to test the property
            //modelInstance.emails shouldBe ("TODO")
        }

        // to test the property `dedup` - Remove duplicate emails
        should("test dedup") {
            // uncomment below to test the property
            //modelInstance.dedup shouldBe ("TODO")
        }

        // to test the property `metadata` - Custom metadata for the job
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `webhookUrl` - URL for completion webhook
        should("test webhookUrl") {
            // uncomment below to test the property
            //modelInstance.webhookUrl shouldBe ("TODO")
        }

        // to test the property `idempotencyKey` - Unique key for idempotent requests
        should("test idempotencyKey") {
            // uncomment below to test the property
            //modelInstance.idempotencyKey shouldBe ("TODO")
        }

    }
}
