/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.DeletePolicy200Response

class DeletePolicy200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeletePolicy200Response
        //val modelInstance = DeletePolicy200Response()

        // to test the property `deleted`
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

        // to test the property `policyId`
        should("test policyId") {
            // uncomment below to test the property
            //modelInstance.policyId shouldBe ("TODO")
        }

    }
}
