/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.JobResponse
import com.mailodds.models.Job

class JobResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JobResponse
        //val modelInstance = JobResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `job`
        should("test job") {
            // uncomment below to test the property
            //modelInstance.job shouldBe ("TODO")
        }

    }
}
