/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.JobSummary

class JobSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JobSummary
        //val modelInstance = JobSummary()

        // to test the property `valid`
        should("test valid") {
            // uncomment below to test the property
            //modelInstance.valid shouldBe ("TODO")
        }

        // to test the property `invalid`
        should("test invalid") {
            // uncomment below to test the property
            //modelInstance.invalid shouldBe ("TODO")
        }

        // to test the property `doNotMail`
        should("test doNotMail") {
            // uncomment below to test the property
            //modelInstance.doNotMail shouldBe ("TODO")
        }

        // to test the property `unknown`
        should("test unknown") {
            // uncomment below to test the property
            //modelInstance.unknown shouldBe ("TODO")
        }

        // to test the property `cancelledPending`
        should("test cancelledPending") {
            // uncomment below to test the property
            //modelInstance.cancelledPending shouldBe ("TODO")
        }

    }
}
