/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.PolicyListResponse
import com.mailodds.models.Policy
import com.mailodds.models.PolicyListResponseLimits

class PolicyListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyListResponse
        //val modelInstance = PolicyListResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `policies`
        should("test policies") {
            // uncomment below to test the property
            //modelInstance.policies shouldBe ("TODO")
        }

        // to test the property `limits`
        should("test limits") {
            // uncomment below to test the property
            //modelInstance.limits shouldBe ("TODO")
        }

    }
}
