/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.PolicyPresetsResponsePresetsInner
import com.mailodds.models.PolicyRule

class PolicyPresetsResponsePresetsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PolicyPresetsResponsePresetsInner
        //val modelInstance = PolicyPresetsResponsePresetsInner()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `rules`
        should("test rules") {
            // uncomment below to test the property
            //modelInstance.rules shouldBe ("TODO")
        }

    }
}
