/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.PresignedUploadResponseUpload

class PresignedUploadResponseUploadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PresignedUploadResponseUpload
        //val modelInstance = PresignedUploadResponseUpload()

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `fields`
        should("test fields") {
            // uncomment below to test the property
            //modelInstance.fields shouldBe ("TODO")
        }

        // to test the property `s3Key`
        should("test s3Key") {
            // uncomment below to test the property
            //modelInstance.s3Key shouldBe ("TODO")
        }

        // to test the property `expiresIn`
        should("test expiresIn") {
            // uncomment below to test the property
            //modelInstance.expiresIn shouldBe ("TODO")
        }

    }
}
