/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.RemoveSuppressionRequest

class RemoveSuppressionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RemoveSuppressionRequest
        //val modelInstance = RemoveSuppressionRequest()

        // to test the property `propertyEntries`
        should("test propertyEntries") {
            // uncomment below to test the property
            //modelInstance.propertyEntries shouldBe ("TODO")
        }

    }
}
