/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.SuppressionCheckResponse

class SuppressionCheckResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuppressionCheckResponse
        //val modelInstance = SuppressionCheckResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `suppressed`
        should("test suppressed") {
            // uncomment below to test the property
            //modelInstance.suppressed shouldBe ("TODO")
        }

        // to test the property `matchType`
        should("test matchType") {
            // uncomment below to test the property
            //modelInstance.matchType shouldBe ("TODO")
        }

        // to test the property `matchValue`
        should("test matchValue") {
            // uncomment below to test the property
            //modelInstance.matchValue shouldBe ("TODO")
        }

    }
}
