/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.SuppressionStatsResponse
import com.mailodds.models.SuppressionStatsResponseByType

class SuppressionStatsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuppressionStatsResponse
        //val modelInstance = SuppressionStatsResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `byType`
        should("test byType") {
            // uncomment below to test the property
            //modelInstance.byType shouldBe ("TODO")
        }

    }
}
