/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.SuppressionListResponse
import com.mailodds.models.Pagination
import com.mailodds.models.SuppressionEntry

class SuppressionListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuppressionListResponse
        //val modelInstance = SuppressionListResponse()

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `propertyEntries`
        should("test propertyEntries") {
            // uncomment below to test the property
            //modelInstance.propertyEntries shouldBe ("TODO")
        }

        // to test the property `pagination`
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
