/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.TelemetrySummaryTotals

class TelemetrySummaryTotalsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetrySummaryTotals
        //val modelInstance = TelemetrySummaryTotals()

        // to test the property `validations` - Total validations in window
        should("test validations") {
            // uncomment below to test the property
            //modelInstance.validations shouldBe ("TODO")
        }

        // to test the property `creditsUsed` - Credits consumed
        should("test creditsUsed") {
            // uncomment below to test the property
            //modelInstance.creditsUsed shouldBe ("TODO")
        }

    }
}
