/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.TelemetrySummaryRates

class TelemetrySummaryRatesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetrySummaryRates
        //val modelInstance = TelemetrySummaryRates()

        // to test the property `deliverable` - Rate of valid + catch_all emails
        should("test deliverable") {
            // uncomment below to test the property
            //modelInstance.deliverable shouldBe ("TODO")
        }

        // to test the property `reject` - Rate of invalid + do_not_mail emails
        should("test reject") {
            // uncomment below to test the property
            //modelInstance.reject shouldBe ("TODO")
        }

        // to test the property `unknown` - Rate of unknown status
        should("test unknown") {
            // uncomment below to test the property
            //modelInstance.unknown shouldBe ("TODO")
        }

        // to test the property `suppressed` - Rate of suppressed emails
        should("test suppressed") {
            // uncomment below to test the property
            //modelInstance.suppressed shouldBe ("TODO")
        }

    }
}
