/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.TestPolicyRequestTestResult

class TestPolicyRequestTestResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestPolicyRequestTestResult
        //val modelInstance = TestPolicyRequestTestResult()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `subStatus`
        should("test subStatus") {
            // uncomment below to test the property
            //modelInstance.subStatus shouldBe ("TODO")
        }

    }
}
