/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.UpdatePolicyRequest

class UpdatePolicyRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdatePolicyRequest
        //val modelInstance = UpdatePolicyRequest()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `isEnabled`
        should("test isEnabled") {
            // uncomment below to test the property
            //modelInstance.isEnabled shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

    }
}
