/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.ValidationResponseSuppressionMatch

class ValidationResponseSuppressionMatchTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationResponseSuppressionMatch
        //val modelInstance = ValidationResponseSuppressionMatch()

        // to test the property `matched`
        should("test matched") {
            // uncomment below to test the property
            //modelInstance.matched shouldBe ("TODO")
        }

        // to test the property `matchType`
        should("test matchType") {
            // uncomment below to test the property
            //modelInstance.matchType shouldBe ("TODO")
        }

        // to test the property `matchValue`
        should("test matchValue") {
            // uncomment below to test the property
            //modelInstance.matchValue shouldBe ("TODO")
        }

    }
}
