/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.ValidationResponse
import com.mailodds.models.ValidationResponseSuppressionMatch

class ValidationResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationResponse
        //val modelInstance = ValidationResponse()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `status` - Validation status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `action` - Recommended action
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `schemaVersion`
        should("test schemaVersion") {
            // uncomment below to test the property
            //modelInstance.schemaVersion shouldBe ("TODO")
        }

        // to test the property `subStatus` - Detailed status reason
        should("test subStatus") {
            // uncomment below to test the property
            //modelInstance.subStatus shouldBe ("TODO")
        }

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `mxFound`
        should("test mxFound") {
            // uncomment below to test the property
            //modelInstance.mxFound shouldBe ("TODO")
        }

        // to test the property `smtpCheck`
        should("test smtpCheck") {
            // uncomment below to test the property
            //modelInstance.smtpCheck shouldBe ("TODO")
        }

        // to test the property `disposable`
        should("test disposable") {
            // uncomment below to test the property
            //modelInstance.disposable shouldBe ("TODO")
        }

        // to test the property `roleAccount`
        should("test roleAccount") {
            // uncomment below to test the property
            //modelInstance.roleAccount shouldBe ("TODO")
        }

        // to test the property `freeProvider`
        should("test freeProvider") {
            // uncomment below to test the property
            //modelInstance.freeProvider shouldBe ("TODO")
        }

        // to test the property `suppressionMatch`
        should("test suppressionMatch") {
            // uncomment below to test the property
            //modelInstance.suppressionMatch shouldBe ("TODO")
        }

    }
}
