/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mailodds.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mailodds.models.ValidationResult

class ValidationResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationResult
        //val modelInstance = ValidationResult()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `subStatus`
        should("test subStatus") {
            // uncomment below to test the property
            //modelInstance.subStatus shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `processedAt`
        should("test processedAt") {
            // uncomment below to test the property
            //modelInstance.processedAt shouldBe ("TODO")
        }

    }
}
