/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.AddSuppressionRequest
import org.openapitools.client.models.AddSuppressionResponse
import org.openapitools.client.models.CheckSuppressionRequest
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.RemoveSuppression200Response
import org.openapitools.client.models.RemoveSuppressionRequest
import org.openapitools.client.models.SuppressionCheckResponse
import org.openapitools.client.models.SuppressionListResponse
import org.openapitools.client.models.SuppressionStatsResponse

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class SuppressionListsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.mailodds.com/v1")
        }
    }

    /**
     * POST /v1/suppression
     * Add suppression entries
     * Add emails or domains to the suppression list.
     * @param addSuppressionRequest 
     * @return AddSuppressionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun addSuppression(addSuppressionRequest: AddSuppressionRequest) : AddSuppressionResponse {
        val localVarResponse = addSuppressionWithHttpInfo(addSuppressionRequest = addSuppressionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AddSuppressionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/suppression
     * Add suppression entries
     * Add emails or domains to the suppression list.
     * @param addSuppressionRequest 
     * @return ApiResponse<AddSuppressionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun addSuppressionWithHttpInfo(addSuppressionRequest: AddSuppressionRequest) : ApiResponse<AddSuppressionResponse?> {
        val localVariableConfig = addSuppressionRequestConfig(addSuppressionRequest = addSuppressionRequest)

        return request<AddSuppressionRequest, AddSuppressionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation addSuppression
     *
     * @param addSuppressionRequest 
     * @return RequestConfig
     */
    fun addSuppressionRequestConfig(addSuppressionRequest: AddSuppressionRequest) : RequestConfig<AddSuppressionRequest> {
        val localVariableBody = addSuppressionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/suppression",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/suppression/check
     * Check suppression status
     * Check if an email is suppressed.
     * @param checkSuppressionRequest 
     * @return SuppressionCheckResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun checkSuppression(checkSuppressionRequest: CheckSuppressionRequest) : SuppressionCheckResponse {
        val localVarResponse = checkSuppressionWithHttpInfo(checkSuppressionRequest = checkSuppressionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SuppressionCheckResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/suppression/check
     * Check suppression status
     * Check if an email is suppressed.
     * @param checkSuppressionRequest 
     * @return ApiResponse<SuppressionCheckResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun checkSuppressionWithHttpInfo(checkSuppressionRequest: CheckSuppressionRequest) : ApiResponse<SuppressionCheckResponse?> {
        val localVariableConfig = checkSuppressionRequestConfig(checkSuppressionRequest = checkSuppressionRequest)

        return request<CheckSuppressionRequest, SuppressionCheckResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation checkSuppression
     *
     * @param checkSuppressionRequest 
     * @return RequestConfig
     */
    fun checkSuppressionRequestConfig(checkSuppressionRequest: CheckSuppressionRequest) : RequestConfig<CheckSuppressionRequest> {
        val localVariableBody = checkSuppressionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/suppression/check",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/suppression/stats
     * Get suppression statistics
     * Get statistics about the suppression list.
     * @return SuppressionStatsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSuppressionStats() : SuppressionStatsResponse {
        val localVarResponse = getSuppressionStatsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SuppressionStatsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/suppression/stats
     * Get suppression statistics
     * Get statistics about the suppression list.
     * @return ApiResponse<SuppressionStatsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getSuppressionStatsWithHttpInfo() : ApiResponse<SuppressionStatsResponse?> {
        val localVariableConfig = getSuppressionStatsRequestConfig()

        return request<Unit, SuppressionStatsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getSuppressionStats
     *
     * @return RequestConfig
     */
    fun getSuppressionStatsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/suppression/stats",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter type
     */
     enum class TypeListSuppression(val value: kotlin.String) {
         @Json(name = "email") email("email"),
         @Json(name = "domain") domain("domain");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /v1/suppression
     * List suppression entries
     * List all suppression entries for the account.
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @return SuppressionListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listSuppression(page: kotlin.Int? = 1, perPage: kotlin.Int? = 50, type: TypeListSuppression? = null, search: kotlin.String? = null) : SuppressionListResponse {
        val localVarResponse = listSuppressionWithHttpInfo(page = page, perPage = perPage, type = type, search = search)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SuppressionListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/suppression
     * List suppression entries
     * List all suppression entries for the account.
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @return ApiResponse<SuppressionListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listSuppressionWithHttpInfo(page: kotlin.Int?, perPage: kotlin.Int?, type: TypeListSuppression?, search: kotlin.String?) : ApiResponse<SuppressionListResponse?> {
        val localVariableConfig = listSuppressionRequestConfig(page = page, perPage = perPage, type = type, search = search)

        return request<Unit, SuppressionListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listSuppression
     *
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 50)
     * @param type  (optional)
     * @param search  (optional)
     * @return RequestConfig
     */
    fun listSuppressionRequestConfig(page: kotlin.Int?, perPage: kotlin.Int?, type: TypeListSuppression?, search: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.value))
                }
                if (search != null) {
                    put("search", listOf(search.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/suppression",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/suppression
     * Remove suppression entries
     * Remove emails or domains from the suppression list.
     * @param removeSuppressionRequest 
     * @return RemoveSuppression200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun removeSuppression(removeSuppressionRequest: RemoveSuppressionRequest) : RemoveSuppression200Response {
        val localVarResponse = removeSuppressionWithHttpInfo(removeSuppressionRequest = removeSuppressionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemoveSuppression200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/suppression
     * Remove suppression entries
     * Remove emails or domains from the suppression list.
     * @param removeSuppressionRequest 
     * @return ApiResponse<RemoveSuppression200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun removeSuppressionWithHttpInfo(removeSuppressionRequest: RemoveSuppressionRequest) : ApiResponse<RemoveSuppression200Response?> {
        val localVariableConfig = removeSuppressionRequestConfig(removeSuppressionRequest = removeSuppressionRequest)

        return request<RemoveSuppressionRequest, RemoveSuppression200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation removeSuppression
     *
     * @param removeSuppressionRequest 
     * @return RequestConfig
     */
    fun removeSuppressionRequestConfig(removeSuppressionRequest: RemoveSuppressionRequest) : RequestConfig<RemoveSuppressionRequest> {
        val localVariableBody = removeSuppressionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/suppression",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
